var pragmadb = db.getSiblingDB('pragmadb');

pragmadb.Bank.save({id: "0001", name: "BANCO DE CHILE"});
pragmadb.Bank.save({id: "0009", name: "BANCO INTERNACIONAL"});
pragmadb.Bank.save({id: "BBH",  name:  "BROWN BROTHERS HARRIMAN"});
pragmadb.Bank.save({id: "BLNY", name: "BANK LEUMI NY"});
pragmadb.Bank.save({id: "0012", name: "BANCO DEL ESTADO DE CHILE"});
pragmadb.Bank.save({id: "0014", name: "SCOTIABANK SUD AMERICANO"});
pragmadb.Bank.save({id: "0016", name: "BANCO DE CREDITO E INVERSIONES"});
pragmadb.Bank.save({id: "0017", name: "BANCO DO BRASIL S.A."});
pragmadb.Bank.save({id: "0018", name: "BANCO CENTRAL DE CHILE"});
pragmadb.Bank.save({id: "0027", name: "CORPBANCA"});
pragmadb.Bank.save({id: "BLU",  name: "BLUBANK"});
pragmadb.Bank.save({id: "0027", name: "CORPBANCA"});
pragmadb.Bank.save({id: "0028", name: "BANCO BICE"});
pragmadb.Bank.save({id: "0031", name: "HSBC BANK (CHILE)"});
pragmadb.Bank.save({id: "0033", name: "CITIBANK N.A"});
pragmadb.Bank.save({id: "0037", name: "BANCO SANTANDER CHILE"});
pragmadb.Bank.save({id: "0039", name: "BANCO ITAU"});
pragmadb.Bank.save({id: "0041", name: "JP MORGAN CHASE BANK N.A."});
pragmadb.Bank.save({id: "0042", name: "AMERICAN EXPRESS BAN"});
pragmadb.Bank.save({id: "0043", name: "BANCO DE LA NACION ARGENTINA"});
pragmadb.Bank.save({id: "0045", name: "THE BANK OF TOKYO-MITSUBISHI LTD"});
pragmadb.Bank.save({id: "CCB",  name: "CHEVY CHASE BANK"});
pragmadb.Bank.save({id: "0049", name: "BANCO SECURITY"});
pragmadb.Bank.save({id: "0051", name: "BANCO FALABELLA"});
pragmadb.Bank.save({id: "0052", name: "DEUTSCHE BANK (CHILE)"});
pragmadb.Bank.save({id: "PB",   name: "PNC BANK"});
pragmadb.Bank.save({id: "0053", name: "BANCO RIPLEY"});
pragmadb.Bank.save({id: "0053", name: "HNS BANCO"});
pragmadb.Bank.save({id: "0055", name: "BANCO MONEX"});
pragmadb.Bank.save({id: "0056", name: "BANCO PENTA"});
pragmadb.Bank.save({id: "0057", name: "BANCO PARIS"});
pragmadb.Bank.save({id: "0507", name: "BANCO DEL DESARROLLO"});
pragmadb.Bank.save({id: "INT", name: "BANCO INTERNACIONAL"});
pragmadb.Bank.save({id: "1000", name: "BANCO BBVA MADRID"});
pragmadb.Bank.save({id: "1001", name: "BANCO STANDARD CHARTERED"});
pragmadb.Bank.save({id: "1002", name: "SALOMON SMITHBARNEYS"});
pragmadb.Bank.save({id: "1003", name: "BEAR STEARNS"});
pragmadb.Bank.save({id: "1004", name: "PICTET"});
pragmadb.Bank.save({id: "1005", name: "ROBECO"});
pragmadb.Bank.save({id: "1006", name: "SGAM"});
pragmadb.Bank.save({id: "1007", name: "NEUBERGER"});
pragmadb.Bank.save({id: "1008", name: "Brown Brothers Harriman Co"});
pragmadb.Bank.save({id: "1009", name: "WACHOVIA BANK"});
pragmadb.Bank.save({id: "WB", name: "WACHOVIA BANK"});

print("All Banks has been saved");
